
kind: PersistentVolume
apiVersion: v1
metadata:
  name: codebeamer-app-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # - ReadWriteMany
  hostPath:
    path: /codebeamer/volume  # Works with only with linux host machines
    type: DirectoryOrCreate  
