kind: PersistentVolume
apiVersion: v1
metadata:
  name: codebeamer-app-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteMany
  hostPath:
    path:  C:\codebeamer\pv
