apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: codebeamer-db-mysql
  name: codebeamer-db-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
