apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: codebeamer-app-search
  name: codebeamer-app-search
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: azurefile
status: {}
