apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: codebeamer-app-tomcat
  name: codebeamer-app-tomcat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: my-azurefile
status: {}
