apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: codebeamer-app-keystore
  name: codebeamer-app-keystore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
#can be deleted?
