kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: my-azurefile
provisioner: file.csi.azure.com # replace with "kubernetes.io/azure-file" if aks version is less than 1.21
allowVolumeExpansion: true
mountOptions:
 - dir_mode=0777  # read/write/execute permissions for all users on directories
 - file_mode=0777 # read/write/execute permissions for all users on files
 - uid=1001       # set the owner User ID 
 - gid=1001       # set the owner Group ID 
 - mfsymlinks     # enable the management of symbolic links
 - nobrl          # byte-range locking ? is used for sharing files among multiple clients and maintaining data integrity
 - cache=none     # no caching used, other values: strict
 - actimeo=30     # attibute cache timeout
parameters:
  skuName: Standard_LRS