apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: codebeamer-full
  name: codebeamer-full
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: codebeamer-full
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/codebeamer-default: "true"
        io.kompose.service: codebeamer-full
    spec:
      containers:
        - name: codebeamer-app
          env:
            - name: CB_database_JDBC_ConnectionURL
              value: jdbc:mysql://codebeamer-db:3306/codebeamer?autoReconnect=true&zeroDateTimeBehavior=convertToNull&emulateLocators=true&characterEncoding=UTF-8&useSSL=false
            - name: CB_database_JDBC_Driver
              value: com.mysql.jdbc.Driver
            - name: CB_database_JDBC_Password
              value: pass
            - name: CB_database_JDBC_Timeout
              value: "120"
            - name: CB_database_JDBC_Username
              value: user
            - name: JVM_OPTIONS
              value: ' -Djdk.tls.ephemeralDHKeySize=4096'
            - name: TOMCAT_CONNECTOR_KEYSTORE_FILE
              value: '/etc/ssl/domain.p12'
            - name: TOMCAT_CONNECTOR_KEYSTORE_PASS
              value: 'Swqa1234!'           
            - name: WAIT_HOSTS
              value: codebeamer-db:3306
            - name: WAIT_HOSTS_TIMEOUT
              value: "120"
          image: codebeameracr.azurecr.io/codebeamer-app:2 # intland/codebeamer:2.0.0.2            
          ports:
            - containerPort: 8090
              hostPort: 9000
              protocol: TCP
          resources: 
            limits:
              memory: "5000Mi" # 5000 MB (min.3410)
              cpu: "5" # 5 CPU cores (min.501)
            requests:
              cpu: "2"
              memory: "3500Mi"
          volumeMounts:
            - mountPath: /etc/ssl  # The mount path
              name: codebeamer-app-keystore
            - mountPath: /home/appuser/codebeamer/repository/config/logo
              name: codebeamer-app-logo
            - mountPath: /home/appuser/codebeamer/repository/docs
              name: codebeamer-app-docs
            - mountPath: /home/appuser/codebeamer/repository/search
              name: codebeamer-app-search
            - mountPath: /home/appuser/codebeamer/logs
              name: codebeamer-app-logs-volume
            - mountPath: /home/appuser/codebeamer/tomcat/tmp
              name: codebeamer-app-tomcat          
        - name: codebeamer-db
          env:
            - name: MYSQL_DATABASE
              value: codebeamer
            - name: MYSQL_INNODB_BUFFER_POOL_SIZE
              value: 1G
            - name: MYSQL_INNODB_LOG_BUFFER_SIZE
              value: 256M
            - name: MYSQL_INNODB_LOG_FILE_SIZE
              value: 256M
            - name: MYSQL_MAX_ALLOWED_PACKET
              value: 1024M
            - name: MYSQL_PASSWORD
              value: pass
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_USER
              value: user
          image: codebeameracr.azurecr.io/codebeamer-db # intland/mysql:debian-8.0.34-utf8mb4 # intland/mysql:debian-8.0.23-utf8mb4          
          ports:
            - containerPort: 3306
              hostPort: 3306
              protocol: TCP
          resources: 
            limits:
              cpu: "100m" # 10% of CPU (min 13)
              memory: "2Gi" # 2000 MB (min 563)             
            requests:
              cpu: "50m"
              memory: "2Gi"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: codebeamer-db-mysql
      imagePullSecrets:
        - name: codebeamer-regcred
      restartPolicy: Always
      volumes:
        - name: codebeamer-app-keystore
          secret:
            secretName: codebeamer-certificate
            items:
              - key: keystore.p12
                path: domain.p12
        - name: codebeamer-app-logo
          persistentVolumeClaim:
            claimName: codebeamer-app-logo
        - name: codebeamer-app-docs
          persistentVolumeClaim:
            claimName: codebeamer-app-docs
        - name: codebeamer-app-search
          persistentVolumeClaim:
            claimName: codebeamer-app-search
        - name: codebeamer-app-logs-volume
          persistentVolumeClaim:
            claimName: codebeamer-app-logs-pvc
        - name: codebeamer-app-tomcat
          persistentVolumeClaim:
            claimName: codebeamer-app-tomcat
        - name: codebeamer-db-mysql
          persistentVolumeClaim:
            claimName: codebeamer-db-mysql
status: {}
